- name: Including network and facts
  import_playbook: fact_gatherer_playbook.yml
  tags:
    - facts

- name: Proxy setup
  hosts: tag_Name_{{ global_var_country_code }}_{{ global_var_product }}_{{ global_var_environment }}_proxy
  # hosts: tag_Name_main_billbox_preprod_proxy
  become: true
  gather_facts: true
  # pre_tasks:
  #   - debug: var=hostvars.localhost.reg_internal_alb_facts.load_balancers.0.dns_name
  roles:
    - role: util
    - role: aws
    - role: networking
    - role: webserver_family
    - role: elasticbeats
    - role: monitoring_family    
  vars_files:
    - "playbook_vars/{{ global_var_environment }}/vault/{{ global_var_environment }}_variables.vault"
    - "playbook_vars/{{ global_var_environment }}/global_vars.yml"
    - "playbook_vars/{{ global_var_environment }}/proxy_default_vars.yml"
    - "playbook_vars/{{ global_var_environment }}/proxy_forward_zw_econet_vars.yml"
    - "playbook_vars/{{ global_var_environment }}/proxy_forward_gh_mtndatabundle_vars.yml"
    - "playbook_vars/{{ global_var_environment }}/proxy_forward_gh_stanbicdatapower_vars.yml"
    - "playbook_vars/{{ global_var_environment }}/proxy_forward_gh_appsnmobairteltigo_vars.yml"
    - "playbook_vars/{{ global_var_environment }}/proxy_forward_zw_ecocash_vars.yml"
    - "playbook_vars/{{ global_var_environment }}/proxy_forward_gh_ghipss_vars.yml"
    - "playbook_vars/{{ global_var_environment }}/proxy_forward_gh_afrxprssairteltigo_vars.yml"
    - "playbook_vars/{{ global_var_environment }}/proxy_forward_gh_afrxprssglo_vars.yml"
    - "playbook_vars/{{ global_var_environment }}/proxy_forward_gh_afrxprssvodafone_vars.yml"
    - "playbook_vars/{{ global_var_environment }}/proxy_forward_gh_airteltigobankintegration_vars.yml"
    - "playbook_vars/{{ global_var_environment }}/proxy_forward_gh_gwcl_vars.yml"
    - "playbook_vars/{{ global_var_environment }}/proxy_forward_gh_vodafonecash_vars.yml"
    - "playbook_vars/{{ global_var_environment }}/proxy_forward_gh_zeepaymomo_vars.yml"
    - "playbook_vars/{{ global_var_environment }}/proxy_forward_gh_mtnfttxbundle_vars.yml"






